# Automatically generated by configure - do not modify
SRC_PATH=/home/lzk/Desktop/qemu_riscv/riscv-qemu-3.0/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
